version: "3.8"

services:
  app:
    build:
      context: ./backend
    secrets:
      - mariadb-password
    networks:
      - backnet
    ports:
      - 56789:56789

  mariadb:
    image: mariadb:latest
    command: '--default-authentication-plugin=auth_ed25519'
    restart: always
    secrets:
      - mariadb-password
    volumes:
      - mariadata:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=ERProject
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mariadb-password

  node:
    build:
      context: ./frontend
    networks:
      - frontnet
    ports:
      - 3000:3000

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodata:/data/db
    networks:
      - frontnet

volumes:
  mongodata:
  mariadata:

secrets:
  mariadb-password:
    file: secrets/mariadb-password.txt

networks:
  backnet:
  frontnet:
